export enum ContainerGap {
    NONE = 'gap-0',
    XXS = 'gap-2',
    XS = 'gap-4',
    SM = 'gap-6',
    MD = 'gap-8',
    LG = 'gap-12',
    XL = 'gap-16',
    X_XS = 'gap-x-4',
    X_SM = 'gap-x-6',
    X_MD = 'gap-x-8',
    X_LG = 'gap-x-12',
    X_XL = 'gap-x-16',
    Y_XS = 'gap-y-4',
    Y_SM = 'gap-y-6',
    Y_MD = 'gap-y-8',
    Y_LG = 'gap-y-12',
    Y_XL = 'gap-y-16',
}